// <auto-generated />
using System;
using BookStoreManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317053117_ThemCotMoTaSach")]
    partial class ThemCotMoTaSach
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStoreManagement.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"));

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnhUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongDaBan")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSach")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSach");

                    b.ToTable("Saches");

                    b.HasData(
                        new
                        {
                            MaSach = 1,
                            GiaBan = 100000m,
                            MoTa = "Cuốn sách cung cấp kiến thức toàn diện về ASP.NET Core, từ cơ bản đến nâng cao, giúp bạn xây dựng website thực tế.",
                            SoLuongDaBan = 0,
                            TacGia = "Nguyễn Văn A",
                            TenSach = "Lập trình ASP.NET Core"
                        },
                        new
                        {
                            MaSach = 2,
                            GiaBan = 120000m,
                            MoTa = "Cuốn sách cung cấp kiến thức toàn diện về ASP.NET Core, từ cơ bản đến nâng cao, giúp bạn xây dựng website thực tế.",
                            SoLuongDaBan = 0,
                            TacGia = "Trần Thị B",
                            TenSach = "Cấu trúc dữ liệu"
                        });
                });

            modelBuilder.Entity("BookStoreManagement.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTK");

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            MaTK = 1,
                            Email = "admin@bookstore.com",
                            HoTen = "NTP",
                            NgayTao = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "123",
                            Role = "Admin",
                            SoDienThoai = "0988888888",
                            Username = "admin"
                        },
                        new
                        {
                            MaTK = 2,
                            Email = "khachhang@gmail.com",
                            HoTen = "khachhang",
                            NgayTao = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "123",
                            Role = "Customer",
                            SoDienThoai = "0909090909",
                            Username = "khach"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
